export const uiText = {
  site: {
    brand: "DELEE",
    adminBrand: "内容后台",
    homeAria: "DELEE 首页",
    metadataTitle: "DELEE - 个人创作档案",
    metadataDescription: "DELEE 的个人创作档案，记录文章、视觉作品、每日更新与 Orask 访客反馈。"
  },
  nav: {
    home: "首页",
    articles: "文章",
    gallery: "画廊",
    orask: "Orask"
  },
  footer: {
    description: "个人创作档案，记录文章、视觉作品、视频和仍在生长的想法。"
  },
  home: {
    intro: "记录想法、进展，以及关于日常的思考。",
    readArticles: "阅读文章",
    viewGallery: "查看画廊",
    heroTitle: "记录创作，整理观察，也保存那些尚未完成的东西。",
    todayUpdates: "今日更新",
    noUpdates: "暂无更新",
    year: "年",
    month: "月",
    day: "日",
    newArchiveTitle: "新加入档案的内容",
    categoryIndex: "分类索引",
    categoryIndexTitle: "最新文章、图片、视频、项目与随笔"
  },
  articles: {
    title: "文章",
    metadataTitle: "文章",
    heroTitle: "文本作品、观察札记、长期想法和创作记录。",
    heroDescription:
      "文章从数据库中的 Markdown 内容读取，按时间倒序排列。分类筛选用于快速进入某一种写作状态。",
    allCategories: "全部",
    backToArticles: "返回文章",
    notFoundTitle: "文章不存在",
    notFoundOrUnpublished: "文章不存在或尚未发布。",
    emptyPreview: "暂无预览内容。"
  },
  gallery: {
    title: "画廊",
    metadataTitle: "画廊",
    heroTitle: "设计，想法的可视化展现。",
    heroDescription:
      "图片可以点击放大预览。视频使用静音循环、移动端内联播放和进入视口后播放的策略，让作品在画廊中直接动起来，同时避免一次性加载过多大文件。",
    closePreview: "关闭",
    previewAriaPrefix: "预览"
  },
  galleryCategories: {
    all: "全部",
    image: "图片",
    video: "视频",
    poster: "海报",
    animation: "动态",
    experiment: "实验"
  },
  updateTypes: {
    article: "文章",
    image: "图片",
    video: "视频",
    note: "随笔",
    project: "项目"
  },
  orask: {
    metadataTitle: "Orask",
    eyebrow: "Or ask?",
    title: "留下一条问题、建议或合作想法。",
    description:
      "Orask 是访客反馈入口。你可以在这里提交建议、问题、合作想法，或任何希望我认真读到的内容。",
    formTitle: "提交你的问题与想法",
    formDescription: "你的每一字，使命必达",
    nameLabel: "访客名字",
    namePlaceholder: "你的名字",
    emailLabel: "访客邮箱",
    subjectLabel: "主题",
    subjectPlaceholder: "建议、合作、问题或其他想法",
    messageLabel: "反馈内容",
    messagePlaceholder: "写下你想让我看到的内容。",
    submit: "提交 Orask",
    submitting: "发送中...",
    validationName: "请填写你的名字。",
    validationEmail: "请填写有效的邮箱地址。",
    validationSubject: "请填写主题。",
    validationMessage: "反馈内容至少需要 10 个字符。",
    sending: "正在发送你的 Orask 留言...",
    success: "已发送，谢谢你留下这条反馈。",
    failure: "发送失败，请稍后再试。",
    unavailable: "暂时无法发送，请稍后再试。"
  },
  notFound: {
    code: "404",
    title: "这条内容还没有进入档案。",
    backHome: "返回首页"
  },
  admin: {
    metadataTitle: "内容后台",
    loginTitle: "后台登录",
    loginHeading: "内容后台",
    loginPanelTitle: "登录后台",
    loginIntro:
      "这是独立的内容管理入口，用来发布文章、画廊作品、每日更新，并查看 Orask 留言。",
    loginHelp: "管理员账号和密码从环境变量读取，不会暴露在前端代码里。",
    username: "用户名",
    password: "密码",
    passwordPlaceholder: "输入后台密码",
    loginSubmit: "进入后台",
    loginSubmitting: "登录中...",
    loginFailed: "登录失败。",
    loggedIn: "已登录",
    viewPublicSite: "查看前台",
    logout: "退出登录",
    navDashboard: "仪表盘",
    navUpdates: "每日更新",
    navArticles: "文章管理",
    navGallery: "画廊管理",
    navOrask: "Orask 留言",
    navSettings: "系统设置",
    dashboardTitle: "仪表盘",
    publishedArticles: "已发布文章",
    draftArticles: "草稿文章",
    galleryWorks: "画廊作品",
    dailyUpdates: "每日更新",
    unreadOrask: "未读 Orask",
    recentUpdates: "最近更新内容",
    recentOrask: "最近 Orask 留言",
    articlesTitle: "文章管理",
    articlesDescription: "管理草稿、已发布文章和 Markdown 内容。",
    newArticle: "新建文章",
    editArticle: "编辑文章",
    importMarkdown: "导入 Markdown",
    articleList: "文章列表",
    backToArticleList: "返回文章列表",
    noArticles: "暂无文章。",
    title: "标题",
    category: "分类",
    type: "类型",
    date: "日期",
    status: "状态",
    actions: "操作",
    search: "搜索",
    searchArticlesPlaceholder: "搜索标题、摘要、分类、标签",
    published: "已发布",
    draft: "草稿",
    edit: "编辑",
    delete: "删除",
    deleteArticleConfirmPrefix: "确定删除",
    generate: "生成",
    publicUrl: "公开链接",
    tagsPlaceholder: "标签，用逗号分隔",
    summaryPlaceholder: "摘要",
    coverImage: "封面图",
    cover: "封面",
    markdownEditor: "Markdown 编辑器",
    markdownPlaceholder: "在这里输入 Markdown 正文",
    livePreview: "实时预览",
    publishPublic: "发布到公开网站",
    saveArticle: "保存文章",
    saving: "保存中...",
    saved: "已保存。",
    loadingArticle: "正在加载文章...",
    loadArticleFailed: "无法加载文章。",
    saveFailed: "保存失败。",
    importArticle: "导入文章",
    importArticleDescription:
      "支持上传 Markdown 单文件，或带本地图片资源的 Markdown ZIP 包。",
    markdownFile: "Markdown 文件",
    markdownZip: "Markdown ZIP 包",
    importMarkdownFile: "导入 Markdown 文件",
    importMarkdownFileDescription:
      "适用于图片已是网络地址或 /uploads/images 路径的 Markdown 文件。",
    importMarkdownZip: "导入 Markdown ZIP 包",
    importMarkdownZipDescription:
      "适用于 Markdown 与本地图片在同一文件夹或压缩包中的场景。",
    uploadDropHint: "拖拽文件到此处，或点击上传",
    statusIdle: "待上传",
    statusUploading: "上传中",
    statusProcessing: "处理中",
    statusSuccess: "成功",
    statusError: "失败",
    uploadingFile: "正在上传文件...",
    processingArticle: "正在解析文章...",
    importFailed: "导入失败。",
    importSuccess: "导入成功。",
    importNetworkError: "网络错误，导入失败。",
    switchToZip: "改用 ZIP 包导入",
    editDraft: "编辑草稿",
    viewArticleList: "查看文章列表",
    previewArticle: "预览文章",
    galleryTitle: "画廊管理",
    galleryDescription: "管理图片、视频、海报和实验作品。",
    newWork: "新增作品",
    editWork: "编辑作品",
    noWorks: "暂无作品。",
    allCategories: "全部分类",
    workAnchor: "锚点链接",
    imageFile: "图片文件",
    videoFile: "视频文件",
    videoCover: "视频封面",
    descriptionPlaceholder: "描述",
    saveWork: "保存作品",
    updatesTitle: "每日更新管理",
    updatesDescription: "按日期倒序管理首页动态。",
    newUpdate: "新增",
    editUpdate: "编辑每日更新",
    newDailyUpdate: "新增每日更新",
    searchUpdatesPlaceholder: "搜索标题、描述或类型",
    noUpdates: "暂无内容。",
    linkPlaceholder: "链接，例如 /articles/my-note",
    save: "保存",
    oraskTitle: "Orask 留言管理",
    oraskDescription: "查看、搜索和处理访客反馈。",
    searchOraskPlaceholder: "搜索名字、邮箱、主题、内容",
    noOrask: "暂无反馈。",
    read: "已读",
    unread: "未读",
    name: "名字：",
    email: "邮箱：",
    source: "来源：",
    unknown: "未知",
    markAs: "标记为",
    chooseFeedback: "请选择一条反馈。",
    settingsTitle: "系统设置",
    passwordTitle: "修改管理员密码",
    passwordHelp:
      "新密码会以哈希形式保存到 .env，不再保留明文 ADMIN_PASSWORD。",
    currentPassword: "当前密码",
    newPasswordPlaceholder: "新密码，至少 8 个字符",
    confirmPassword: "再次输入新密码",
    saveNewPassword: "保存新密码",
    passwordFailed: "密码修改失败。",
    passwordSuccess: "密码已更新。下次登录请使用新密码。",
    selectFile: "选择文件",
    clear: "清空",
    uploadComplete: "上传完成",
    uploadFailed: "上传失败",
    uploadNetworkError: "网络错误，上传失败"
  },
  apiMessages: {
    incompleteSubmission: "提交内容不完整。",
    unauthorized: "未登录或登录已过期。",
    invalidDate: "日期格式必须为 YYYY-MM-DD",
    inputUsername: "请输入用户名",
    inputPassword: "请输入密码",
    inputCurrentPassword: "请输入当前密码",
    newPasswordTooShort: "新密码至少需要 8 个字符",
    confirmPasswordRequired: "请再次输入新密码",
    passwordMismatch: "两次输入的新密码不一致",
    inputTitle: "请输入标题",
    inputDescription: "请输入描述",
    inputSlug: "请输入 slug",
    invalidSlug: "slug 只能包含小写字母、数字和连字符",
    inputCategory: "请输入分类",
    inputSummary: "请输入摘要",
    inputContent: "请输入正文",
    inputFileUrl: "请上传或填写文件地址",
    invalidCredentials: "用户名或密码不正确。",
    currentPasswordIncorrect: "当前密码不正确。",
    loggedOut: "已退出登录。",
    duplicateSlug: "slug 已存在，请换一个。",
    articleMissing: "文章不存在。",
    workMissing: "作品不存在。",
    updateMissing: "更新内容不存在。",
    feedbackMissing: "反馈不存在。",
    uploadMarkdown: "请上传 Markdown 文件。",
    markdownOnlyLegacy: "只支持 .md 或 .markdown 文件。",
    markdownMimeOnly: "只允许 text/markdown 类型的 Markdown 文件。",
    markdownOnly: "只支持 .md 和 .markdown 文件。",
    markdownTextOnly: "只支持 Markdown 文本文件。",
    markdownTooLargeLegacy: "Markdown 文件不能超过 5MB。",
    markdownTooLarge: "Markdown 文件大小不能超过 5MB。",
    markdownHasLocalImages:
      "该 Markdown 包含本地图片，请改用 Markdown ZIP 包导入，系统会自动上传并重写图片路径。",
    localImagesKeyword: "本地图片",
    uploadZip: "请上传 ZIP 压缩包。",
    zipOnly: "只支持 .zip 压缩包。",
    zipMimeOnly: "只支持 ZIP 压缩包。",
    zipTooLarge: "ZIP 压缩包大小不能超过 25MB。",
    zipImportFailed: "ZIP 导入失败，请检查压缩包结构。",
    uploadImage: "请上传图片文件。",
    uploadVideo: "请上传视频文件。",
    imageUploadFailed: "图片上传失败。",
    videoUploadFailed: "视频上传失败。",
    unsupportedFileType: "不支持的文件类型",
    unknownFileType: "unknown",
    mimeMismatch: "文件 MIME 类型不符合要求。",
    fileTooLargePrefix: "文件过大，最大允许",
    oraskNameRequired: "请填写你的名字。",
    oraskEmailInvalid: "请填写有效的邮箱地址。",
    oraskSubjectRequired: "请填写主题。",
    oraskMessageTooShort: "反馈内容至少需要 10 个字符。",
    oraskMessageTooLong: "反馈内容过长。",
    invalidRequestBody: "请求内容格式不正确。",
    checkForm: "请检查表单内容。",
    feedbackSaveFailed: "留言暂时无法保存，请稍后再试。",
    feedbackSavedAndSent: "Orask 留言已保存并发送。",
    feedbackSavedMailFailed: "留言已保存，但邮件暂时发送失败。我仍然可以在后台看到这条反馈。"
  },
  mail: {
    visitorName: "访客名字",
    visitorEmail: "访客邮箱",
    subject: "主题",
    submittedAt: "提交时间",
    sourcePage: "来源页面",
    newOrask: "新的 Orask 留言"
  }
} as const;
